name: Build and upload a package to PyPI

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: Optional suffix if there's >1 release today. Recommended to leave blank.
        required: false
        type: string

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo '${{ inputs.version_suffix }}'
          if [[ '${{ inputs.version_suffix }}' ]]; then
            echo 'yes'
          else
            echo 'no'
          fi
